# Generated by Django 3.2.9 on 2021-12-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_user_messages_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.TextField(max_length=25, unique=True),
        ),
    ]
